// <auto-generated />
using System;
using DatingBot.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DatingBot.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260821202057_Add_Cities_And_AiVector")]
    partial class Add_Cities_And_AiVector
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DatingBot.Domain.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Region")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Cities_Name");

                    b.HasIndex("Latitude", "Longitude")
                        .HasDatabaseName("IX_Cities_Coordinates");

                    b.ToTable("Cities", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Country = "Россия",
                            Latitude = 55.755800000000001,
                            Longitude = 37.6173,
                            Name = "Москва",
                            Region = "Москва"
                        },
                        new
                        {
                            Id = 2,
                            Country = "Россия",
                            Latitude = 55.896999999999998,
                            Longitude = 37.429699999999997,
                            Name = "Химки",
                            Region = "Московская область"
                        },
                        new
                        {
                            Id = 3,
                            Country = "Россия",
                            Latitude = 55.796300000000002,
                            Longitude = 37.938200000000002,
                            Name = "Балашиха",
                            Region = "Московская область"
                        },
                        new
                        {
                            Id = 4,
                            Country = "Россия",
                            Latitude = 55.431199999999997,
                            Longitude = 37.5458,
                            Name = "Подольск",
                            Region = "Московская область"
                        },
                        new
                        {
                            Id = 5,
                            Country = "Россия",
                            Latitude = 55.9116,
                            Longitude = 37.730800000000002,
                            Name = "Мытищи",
                            Region = "Московская область"
                        },
                        new
                        {
                            Id = 6,
                            Country = "Россия",
                            Latitude = 55.677199999999999,
                            Longitude = 37.8932,
                            Name = "Люберцы",
                            Region = "Московская область"
                        },
                        new
                        {
                            Id = 7,
                            Country = "Россия",
                            Latitude = 55.914200000000001,
                            Longitude = 37.828699999999998,
                            Name = "Королёв",
                            Region = "Московская область"
                        },
                        new
                        {
                            Id = 8,
                            Country = "Россия",
                            Latitude = 55.831099999999999,
                            Longitude = 37.329700000000003,
                            Name = "Красногорск",
                            Region = "Московская область"
                        },
                        new
                        {
                            Id = 9,
                            Country = "Россия",
                            Latitude = 55.678899999999999,
                            Longitude = 37.264400000000002,
                            Name = "Одинцово",
                            Region = "Московская область"
                        },
                        new
                        {
                            Id = 10,
                            Country = "Россия",
                            Latitude = 55.436900000000001,
                            Longitude = 37.767499999999998,
                            Name = "Домодедово",
                            Region = "Московская область"
                        },
                        new
                        {
                            Id = 11,
                            Country = "Россия",
                            Latitude = 55.923400000000001,
                            Longitude = 37.998600000000003,
                            Name = "Щёлково",
                            Region = "Московская область"
                        },
                        new
                        {
                            Id = 12,
                            Country = "Россия",
                            Latitude = 54.915599999999998,
                            Longitude = 37.416699999999999,
                            Name = "Серпухов",
                            Region = "Московская область"
                        },
                        new
                        {
                            Id = 13,
                            Country = "Россия",
                            Latitude = 55.093899999999998,
                            Longitude = 38.768099999999997,
                            Name = "Коломна",
                            Region = "Московская область"
                        },
                        new
                        {
                            Id = 14,
                            Country = "Россия",
                            Latitude = 55.566699999999997,
                            Longitude = 38.2333,
                            Name = "Раменское",
                            Region = "Московская область"
                        },
                        new
                        {
                            Id = 15,
                            Country = "Россия",
                            Latitude = 55.934399999999997,
                            Longitude = 37.514200000000002,
                            Name = "Долгопрудный",
                            Region = "Московская область"
                        },
                        new
                        {
                            Id = 16,
                            Country = "Россия",
                            Latitude = 55.761099999999999,
                            Longitude = 37.861699999999999,
                            Name = "Реутов",
                            Region = "Московская область"
                        },
                        new
                        {
                            Id = 17,
                            Country = "Россия",
                            Latitude = 56.010599999999997,
                            Longitude = 37.847200000000001,
                            Name = "Пушкино",
                            Region = "Московская область"
                        },
                        new
                        {
                            Id = 18,
                            Country = "Россия",
                            Latitude = 55.595300000000002,
                            Longitude = 38.1203,
                            Name = "Жуковский",
                            Region = "Московская область"
                        },
                        new
                        {
                            Id = 19,
                            Country = "Россия",
                            Latitude = 55.854199999999999,
                            Longitude = 38.441699999999997,
                            Name = "Ногинск",
                            Region = "Московская область"
                        },
                        new
                        {
                            Id = 20,
                            Country = "Россия",
                            Latitude = 56.315300000000001,
                            Longitude = 38.136099999999999,
                            Name = "Сергиев Посад",
                            Region = "Московская область"
                        },
                        new
                        {
                            Id = 21,
                            Country = "Россия",
                            Latitude = 59.9343,
                            Longitude = 30.335100000000001,
                            Name = "Санкт-Петербург",
                            Region = "Санкт-Петербург"
                        },
                        new
                        {
                            Id = 22,
                            Country = "Россия",
                            Latitude = 59.566699999999997,
                            Longitude = 30.133299999999998,
                            Name = "Гатчина",
                            Region = "Ленинградская область"
                        },
                        new
                        {
                            Id = 23,
                            Country = "Россия",
                            Latitude = 60.710000000000001,
                            Longitude = 28.749700000000001,
                            Name = "Выборг",
                            Region = "Ленинградская область"
                        },
                        new
                        {
                            Id = 24,
                            Country = "Россия",
                            Latitude = 54.7104,
                            Longitude = 20.452200000000001,
                            Name = "Калининград",
                            Region = "Калининградская область"
                        },
                        new
                        {
                            Id = 25,
                            Country = "Россия",
                            Latitude = 64.547200000000004,
                            Longitude = 40.560200000000002,
                            Name = "Архангельск",
                            Region = "Архангельская область"
                        },
                        new
                        {
                            Id = 26,
                            Country = "Россия",
                            Latitude = 64.563599999999994,
                            Longitude = 39.830199999999998,
                            Name = "Северодвинск",
                            Region = "Архангельская область"
                        },
                        new
                        {
                            Id = 27,
                            Country = "Россия",
                            Latitude = 68.958500000000001,
                            Longitude = 33.082700000000003,
                            Name = "Мурманск",
                            Region = "Мурманская область"
                        },
                        new
                        {
                            Id = 28,
                            Country = "Россия",
                            Latitude = 61.7849,
                            Longitude = 34.346899999999998,
                            Name = "Петрозаводск",
                            Region = "Республика Карелия"
                        },
                        new
                        {
                            Id = 29,
                            Country = "Россия",
                            Latitude = 58.522799999999997,
                            Longitude = 31.2697,
                            Name = "Великий Новгород",
                            Region = "Новгородская область"
                        },
                        new
                        {
                            Id = 30,
                            Country = "Россия",
                            Latitude = 57.813600000000001,
                            Longitude = 28.349599999999999,
                            Name = "Псков",
                            Region = "Псковская область"
                        },
                        new
                        {
                            Id = 31,
                            Country = "Россия",
                            Latitude = 59.133299999999998,
                            Longitude = 37.899999999999999,
                            Name = "Череповец",
                            Region = "Вологодская область"
                        },
                        new
                        {
                            Id = 32,
                            Country = "Россия",
                            Latitude = 59.220500000000001,
                            Longitude = 39.891500000000001,
                            Name = "Вологда",
                            Region = "Вологодская область"
                        },
                        new
                        {
                            Id = 33,
                            Country = "Россия",
                            Latitude = 61.668799999999997,
                            Longitude = 50.835599999999999,
                            Name = "Сыктывкар",
                            Region = "Республика Коми"
                        },
                        new
                        {
                            Id = 34,
                            Country = "Россия",
                            Latitude = 51.660800000000002,
                            Longitude = 39.200299999999999,
                            Name = "Воронеж",
                            Region = "Воронежская область"
                        },
                        new
                        {
                            Id = 35,
                            Country = "Россия",
                            Latitude = 57.626100000000001,
                            Longitude = 39.884500000000003,
                            Name = "Ярославль",
                            Region = "Ярославская область"
                        },
                        new
                        {
                            Id = 36,
                            Country = "Россия",
                            Latitude = 58.048299999999998,
                            Longitude = 38.8583,
                            Name = "Рыбинск",
                            Region = "Ярославская область"
                        },
                        new
                        {
                            Id = 37,
                            Country = "Россия",
                            Latitude = 54.609499999999997,
                            Longitude = 39.712600000000002,
                            Name = "Рязань",
                            Region = "Рязанская область"
                        },
                        new
                        {
                            Id = 38,
                            Country = "Россия",
                            Latitude = 52.610300000000002,
                            Longitude = 39.594700000000003,
                            Name = "Липецк",
                            Region = "Липецкая область"
                        },
                        new
                        {
                            Id = 39,
                            Country = "Россия",
                            Latitude = 54.196100000000001,
                            Longitude = 37.618200000000002,
                            Name = "Тула",
                            Region = "Тульская область"
                        },
                        new
                        {
                            Id = 40,
                            Country = "Россия",
                            Latitude = 54.011400000000002,
                            Longitude = 38.293599999999998,
                            Name = "Новомосковск",
                            Region = "Тульская область"
                        },
                        new
                        {
                            Id = 41,
                            Country = "Россия",
                            Latitude = 51.730400000000003,
                            Longitude = 36.192700000000002,
                            Name = "Курск",
                            Region = "Курская область"
                        },
                        new
                        {
                            Id = 42,
                            Country = "Россия",
                            Latitude = 56.858699999999999,
                            Longitude = 35.9176,
                            Name = "Тверь",
                            Region = "Тверская область"
                        },
                        new
                        {
                            Id = 43,
                            Country = "Россия",
                            Latitude = 56.997199999999999,
                            Longitude = 40.971400000000003,
                            Name = "Иваново",
                            Region = "Ивановская область"
                        },
                        new
                        {
                            Id = 44,
                            Country = "Россия",
                            Latitude = 53.243600000000001,
                            Longitude = 34.363399999999999,
                            Name = "Брянск",
                            Region = "Брянская область"
                        },
                        new
                        {
                            Id = 45,
                            Country = "Россия",
                            Latitude = 50.595399999999998,
                            Longitude = 36.587299999999999,
                            Name = "Белгород",
                            Region = "Белгородская область"
                        },
                        new
                        {
                            Id = 46,
                            Country = "Россия",
                            Latitude = 51.296900000000001,
                            Longitude = 37.834400000000002,
                            Name = "Старый Оскол",
                            Region = "Белгородская область"
                        },
                        new
                        {
                            Id = 47,
                            Country = "Россия",
                            Latitude = 56.128999999999998,
                            Longitude = 40.406599999999997,
                            Name = "Владимир",
                            Region = "Владимирская область"
                        },
                        new
                        {
                            Id = 48,
                            Country = "Россия",
                            Latitude = 56.357199999999999,
                            Longitude = 41.319200000000002,
                            Name = "Ковров",
                            Region = "Владимирская область"
                        },
                        new
                        {
                            Id = 49,
                            Country = "Россия",
                            Latitude = 55.575000000000003,
                            Longitude = 42.052799999999998,
                            Name = "Муром",
                            Region = "Владимирская область"
                        },
                        new
                        {
                            Id = 50,
                            Country = "Россия",
                            Latitude = 54.529299999999999,
                            Longitude = 36.275399999999998,
                            Name = "Калуга",
                            Region = "Калужская область"
                        },
                        new
                        {
                            Id = 51,
                            Country = "Россия",
                            Latitude = 55.100000000000001,
                            Longitude = 36.616700000000002,
                            Name = "Обнинск",
                            Region = "Калужская область"
                        },
                        new
                        {
                            Id = 52,
                            Country = "Россия",
                            Latitude = 54.782600000000002,
                            Longitude = 32.045299999999997,
                            Name = "Смоленск",
                            Region = "Смоленская область"
                        },
                        new
                        {
                            Id = 53,
                            Country = "Россия",
                            Latitude = 52.9651,
                            Longitude = 36.078499999999998,
                            Name = "Орёл",
                            Region = "Орловская область"
                        },
                        new
                        {
                            Id = 54,
                            Country = "Россия",
                            Latitude = 52.731699999999996,
                            Longitude = 41.452199999999998,
                            Name = "Тамбов",
                            Region = "Тамбовская область"
                        },
                        new
                        {
                            Id = 55,
                            Country = "Россия",
                            Latitude = 57.766500000000001,
                            Longitude = 40.926900000000003,
                            Name = "Кострома",
                            Region = "Костромская область"
                        },
                        new
                        {
                            Id = 56,
                            Country = "Россия",
                            Latitude = 55.788699999999999,
                            Longitude = 49.122100000000003,
                            Name = "Казань",
                            Region = "Республика Татарстан"
                        },
                        new
                        {
                            Id = 57,
                            Country = "Россия",
                            Latitude = 55.743600000000001,
                            Longitude = 52.4161,
                            Name = "Набережные Челны",
                            Region = "Республика Татарстан"
                        },
                        new
                        {
                            Id = 58,
                            Country = "Россия",
                            Latitude = 55.635800000000003,
                            Longitude = 51.817799999999998,
                            Name = "Нижнекамск",
                            Region = "Республика Татарстан"
                        },
                        new
                        {
                            Id = 59,
                            Country = "Россия",
                            Latitude = 54.901400000000002,
                            Longitude = 52.297199999999997,
                            Name = "Альметьевск",
                            Region = "Республика Татарстан"
                        },
                        new
                        {
                            Id = 60,
                            Country = "Россия",
                            Latitude = 56.296500000000002,
                            Longitude = 43.936100000000003,
                            Name = "Нижний Новгород",
                            Region = "Нижегородская область"
                        },
                        new
                        {
                            Id = 61,
                            Country = "Россия",
                            Latitude = 56.238900000000001,
                            Longitude = 43.463099999999997,
                            Name = "Дзержинск",
                            Region = "Нижегородская область"
                        },
                        new
                        {
                            Id = 62,
                            Country = "Россия",
                            Latitude = 55.3949,
                            Longitude = 43.8399,
                            Name = "Арзамас",
                            Region = "Нижегородская область"
                        },
                        new
                        {
                            Id = 63,
                            Country = "Россия",
                            Latitude = 53.195900000000002,
                            Longitude = 50.100200000000001,
                            Name = "Самара",
                            Region = "Самарская область"
                        },
                        new
                        {
                            Id = 64,
                            Country = "Россия",
                            Latitude = 53.530299999999997,
                            Longitude = 49.3461,
                            Name = "Тольятти",
                            Region = "Самарская область"
                        },
                        new
                        {
                            Id = 65,
                            Country = "Россия",
                            Latitude = 53.1556,
                            Longitude = 48.4681,
                            Name = "Сызрань",
                            Region = "Самарская область"
                        },
                        new
                        {
                            Id = 66,
                            Country = "Россия",
                            Latitude = 53.097499999999997,
                            Longitude = 49.9328,
                            Name = "Новокуйбышевск",
                            Region = "Самарская область"
                        },
                        new
                        {
                            Id = 67,
                            Country = "Россия",
                            Latitude = 54.738799999999998,
                            Longitude = 55.972099999999998,
                            Name = "Уфа",
                            Region = "Республика Башкортостан"
                        },
                        new
                        {
                            Id = 68,
                            Country = "Россия",
                            Latitude = 53.633299999999998,
                            Longitude = 55.950000000000003,
                            Name = "Стерлитамак",
                            Region = "Республика Башкортостан"
                        },
                        new
                        {
                            Id = 69,
                            Country = "Россия",
                            Latitude = 53.363900000000001,
                            Longitude = 55.924399999999999,
                            Name = "Салават",
                            Region = "Республика Башкортостан"
                        },
                        new
                        {
                            Id = 70,
                            Country = "Россия",
                            Latitude = 56.091700000000003,
                            Longitude = 54.2667,
                            Name = "Нефтекамск",
                            Region = "Республика Башкортостан"
                        },
                        new
                        {
                            Id = 71,
                            Country = "Россия",
                            Latitude = 54.481499999999997,
                            Longitude = 53.470999999999997,
                            Name = "Октябрьский",
                            Region = "Республика Башкортостан"
                        },
                        new
                        {
                            Id = 72,
                            Country = "Россия",
                            Latitude = 58.0105,
                            Longitude = 56.2502,
                            Name = "Пермь",
                            Region = "Пермский край"
                        },
                        new
                        {
                            Id = 73,
                            Country = "Россия",
                            Latitude = 59.416699999999999,
                            Longitude = 56.816699999999997,
                            Name = "Березники",
                            Region = "Пермский край"
                        },
                        new
                        {
                            Id = 74,
                            Country = "Россия",
                            Latitude = 51.5336,
                            Longitude = 46.034300000000002,
                            Name = "Саратов",
                            Region = "Саратовская область"
                        },
                        new
                        {
                            Id = 75,
                            Country = "Россия",
                            Latitude = 51.5,
                            Longitude = 46.116700000000002,
                            Name = "Энгельс",
                            Region = "Саратовская область"
                        },
                        new
                        {
                            Id = 76,
                            Country = "Россия",
                            Latitude = 52.033299999999997,
                            Longitude = 47.783299999999997,
                            Name = "Балаково",
                            Region = "Саратовская область"
                        },
                        new
                        {
                            Id = 77,
                            Country = "Россия",
                            Latitude = 56.852600000000002,
                            Longitude = 53.206899999999997,
                            Name = "Ижевск",
                            Region = "Удмуртская Республика"
                        },
                        new
                        {
                            Id = 78,
                            Country = "Россия",
                            Latitude = 54.3142,
                            Longitude = 48.403100000000002,
                            Name = "Ульяновск",
                            Region = "Ульяновская область"
                        },
                        new
                        {
                            Id = 79,
                            Country = "Россия",
                            Latitude = 54.213799999999999,
                            Longitude = 49.618899999999996,
                            Name = "Димитровград",
                            Region = "Ульяновская область"
                        },
                        new
                        {
                            Id = 80,
                            Country = "Россия",
                            Latitude = 51.766599999999997,
                            Longitude = 55.096899999999998,
                            Name = "Оренбург",
                            Region = "Оренбургская область"
                        },
                        new
                        {
                            Id = 81,
                            Country = "Россия",
                            Latitude = 51.200000000000003,
                            Longitude = 58.566699999999997,
                            Name = "Орск",
                            Region = "Оренбургская область"
                        },
                        new
                        {
                            Id = 82,
                            Country = "Россия",
                            Latitude = 53.200699999999998,
                            Longitude = 45.004600000000003,
                            Name = "Пенза",
                            Region = "Пензенская область"
                        },
                        new
                        {
                            Id = 83,
                            Country = "Россия",
                            Latitude = 58.603499999999997,
                            Longitude = 49.667900000000003,
                            Name = "Киров",
                            Region = "Кировская область"
                        },
                        new
                        {
                            Id = 84,
                            Country = "Россия",
                            Latitude = 56.143900000000002,
                            Longitude = 47.248899999999999,
                            Name = "Чебоксары",
                            Region = "Чувашская Республика"
                        },
                        new
                        {
                            Id = 85,
                            Country = "Россия",
                            Latitude = 56.121899999999997,
                            Longitude = 47.476399999999998,
                            Name = "Новочебоксарск",
                            Region = "Чувашская Республика"
                        },
                        new
                        {
                            Id = 86,
                            Country = "Россия",
                            Latitude = 54.183799999999998,
                            Longitude = 45.183799999999998,
                            Name = "Саранск",
                            Region = "Республика Мордовия"
                        },
                        new
                        {
                            Id = 87,
                            Country = "Россия",
                            Latitude = 56.638800000000003,
                            Longitude = 47.886800000000001,
                            Name = "Йошкар-Ола",
                            Region = "Республика Марий Эл"
                        },
                        new
                        {
                            Id = 88,
                            Country = "Россия",
                            Latitude = 47.235700000000001,
                            Longitude = 39.701500000000003,
                            Name = "Ростов-на-Дону",
                            Region = "Ростовская область"
                        },
                        new
                        {
                            Id = 89,
                            Country = "Россия",
                            Latitude = 47.236199999999997,
                            Longitude = 38.896900000000002,
                            Name = "Таганрог",
                            Region = "Ростовская область"
                        },
                        new
                        {
                            Id = 90,
                            Country = "Россия",
                            Latitude = 47.708599999999997,
                            Longitude = 40.216099999999997,
                            Name = "Шахты",
                            Region = "Ростовская область"
                        },
                        new
                        {
                            Id = 91,
                            Country = "Россия",
                            Latitude = 47.422199999999997,
                            Longitude = 40.092799999999997,
                            Name = "Новочеркасск",
                            Region = "Ростовская область"
                        },
                        new
                        {
                            Id = 92,
                            Country = "Россия",
                            Latitude = 47.513300000000001,
                            Longitude = 42.153100000000002,
                            Name = "Волгодонск",
                            Region = "Ростовская область"
                        },
                        new
                        {
                            Id = 93,
                            Country = "Россия",
                            Latitude = 47.139699999999998,
                            Longitude = 39.7517,
                            Name = "Батайск",
                            Region = "Ростовская область"
                        },
                        new
                        {
                            Id = 94,
                            Country = "Россия",
                            Latitude = 45.035499999999999,
                            Longitude = 38.975299999999997,
                            Name = "Краснодар",
                            Region = "Краснодарский край"
                        },
                        new
                        {
                            Id = 95,
                            Country = "Россия",
                            Latitude = 43.602800000000002,
                            Longitude = 39.734200000000001,
                            Name = "Сочи",
                            Region = "Краснодарский край"
                        },
                        new
                        {
                            Id = 96,
                            Country = "Россия",
                            Latitude = 44.724400000000003,
                            Longitude = 37.767499999999998,
                            Name = "Новороссийск",
                            Region = "Краснодарский край"
                        },
                        new
                        {
                            Id = 97,
                            Country = "Россия",
                            Latitude = 45.001100000000001,
                            Longitude = 41.1233,
                            Name = "Армавир",
                            Region = "Краснодарский край"
                        },
                        new
                        {
                            Id = 98,
                            Country = "Россия",
                            Latitude = 44.8947,
                            Longitude = 37.316400000000002,
                            Name = "Анапа",
                            Region = "Краснодарский край"
                        },
                        new
                        {
                            Id = 99,
                            Country = "Россия",
                            Latitude = 44.561100000000003,
                            Longitude = 38.076700000000002,
                            Name = "Геленджик",
                            Region = "Краснодарский край"
                        },
                        new
                        {
                            Id = 100,
                            Country = "Россия",
                            Latitude = 48.707999999999998,
                            Longitude = 44.513300000000001,
                            Name = "Волгоград",
                            Region = "Волгоградская область"
                        },
                        new
                        {
                            Id = 101,
                            Country = "Россия",
                            Latitude = 48.785800000000002,
                            Longitude = 44.779699999999998,
                            Name = "Волжский",
                            Region = "Волгоградская область"
                        },
                        new
                        {
                            Id = 102,
                            Country = "Россия",
                            Latitude = 50.083300000000001,
                            Longitude = 45.399999999999999,
                            Name = "Камышин",
                            Region = "Волгоградская область"
                        },
                        new
                        {
                            Id = 103,
                            Country = "Россия",
                            Latitude = 46.349699999999999,
                            Longitude = 48.040799999999997,
                            Name = "Астрахань",
                            Region = "Астраханская область"
                        },
                        new
                        {
                            Id = 104,
                            Country = "Россия",
                            Latitude = 45.0428,
                            Longitude = 41.973399999999998,
                            Name = "Ставрополь",
                            Region = "Ставропольский край"
                        },
                        new
                        {
                            Id = 105,
                            Country = "Россия",
                            Latitude = 44.049999999999997,
                            Longitude = 43.066699999999997,
                            Name = "Пятигорск",
                            Region = "Ставропольский край"
                        },
                        new
                        {
                            Id = 106,
                            Country = "Россия",
                            Latitude = 43.9133,
                            Longitude = 42.720799999999997,
                            Name = "Кисловодск",
                            Region = "Ставропольский край"
                        },
                        new
                        {
                            Id = 107,
                            Country = "Россия",
                            Latitude = 44.043599999999998,
                            Longitude = 42.859400000000001,
                            Name = "Ессентуки",
                            Region = "Ставропольский край"
                        },
                        new
                        {
                            Id = 108,
                            Country = "Россия",
                            Latitude = 44.633299999999998,
                            Longitude = 41.933300000000003,
                            Name = "Невинномысск",
                            Region = "Ставропольский край"
                        },
                        new
                        {
                            Id = 109,
                            Country = "Россия",
                            Latitude = 42.984900000000003,
                            Longitude = 47.504600000000003,
                            Name = "Махачкала",
                            Region = "Республика Дагестан"
                        },
                        new
                        {
                            Id = 110,
                            Country = "Россия",
                            Latitude = 43.25,
                            Longitude = 46.583300000000001,
                            Name = "Хасавюрт",
                            Region = "Республика Дагестан"
                        },
                        new
                        {
                            Id = 111,
                            Country = "Россия",
                            Latitude = 42.067799999999998,
                            Longitude = 48.289900000000003,
                            Name = "Дербент",
                            Region = "Республика Дагестан"
                        },
                        new
                        {
                            Id = 112,
                            Country = "Россия",
                            Latitude = 42.881700000000002,
                            Longitude = 47.640599999999999,
                            Name = "Каспийск",
                            Region = "Республика Дагестан"
                        },
                        new
                        {
                            Id = 113,
                            Country = "Россия",
                            Latitude = 43.036700000000003,
                            Longitude = 44.6678,
                            Name = "Владикавказ",
                            Region = "Республика Северная Осетия"
                        },
                        new
                        {
                            Id = 114,
                            Country = "Россия",
                            Latitude = 43.317900000000002,
                            Longitude = 45.6982,
                            Name = "Грозный",
                            Region = "Чеченская Республика"
                        },
                        new
                        {
                            Id = 115,
                            Country = "Россия",
                            Latitude = 43.498100000000001,
                            Longitude = 43.618899999999996,
                            Name = "Нальчик",
                            Region = "Кабардино-Балкарская Республика"
                        },
                        new
                        {
                            Id = 116,
                            Country = "Россия",
                            Latitude = 44.608899999999998,
                            Longitude = 40.1006,
                            Name = "Майкоп",
                            Region = "Республика Адыгея"
                        },
                        new
                        {
                            Id = 117,
                            Country = "Россия",
                            Latitude = 44.223300000000002,
                            Longitude = 42.0578,
                            Name = "Черкесск",
                            Region = "Карачаево-Черкесская Республика"
                        },
                        new
                        {
                            Id = 118,
                            Country = "Россия",
                            Latitude = 46.3078,
                            Longitude = 44.255800000000001,
                            Name = "Элиста",
                            Region = "Республика Калмыкия"
                        },
                        new
                        {
                            Id = 119,
                            Country = "Россия",
                            Latitude = 44.952100000000002,
                            Longitude = 34.102400000000003,
                            Name = "Симферополь",
                            Region = "Республика Крым"
                        },
                        new
                        {
                            Id = 120,
                            Country = "Россия",
                            Latitude = 44.616700000000002,
                            Longitude = 33.525399999999998,
                            Name = "Севастополь",
                            Region = "Севастополь"
                        },
                        new
                        {
                            Id = 121,
                            Country = "Россия",
                            Latitude = 45.356200000000001,
                            Longitude = 36.467399999999998,
                            Name = "Керчь",
                            Region = "Республика Крым"
                        },
                        new
                        {
                            Id = 122,
                            Country = "Россия",
                            Latitude = 45.190399999999997,
                            Longitude = 33.366799999999998,
                            Name = "Евпатория",
                            Region = "Республика Крым"
                        },
                        new
                        {
                            Id = 123,
                            Country = "Россия",
                            Latitude = 56.838900000000002,
                            Longitude = 60.605699999999999,
                            Name = "Екатеринбург",
                            Region = "Свердловская область"
                        },
                        new
                        {
                            Id = 124,
                            Country = "Россия",
                            Latitude = 57.919400000000003,
                            Longitude = 59.965000000000003,
                            Name = "Нижний Тагил",
                            Region = "Свердловская область"
                        },
                        new
                        {
                            Id = 125,
                            Country = "Россия",
                            Latitude = 56.418500000000002,
                            Longitude = 61.9163,
                            Name = "Каменск-Уральский",
                            Region = "Свердловская область"
                        },
                        new
                        {
                            Id = 126,
                            Country = "Россия",
                            Latitude = 56.908099999999997,
                            Longitude = 59.943100000000001,
                            Name = "Первоуральск",
                            Region = "Свердловская область"
                        },
                        new
                        {
                            Id = 127,
                            Country = "Россия",
                            Latitude = 55.164400000000001,
                            Longitude = 61.436799999999998,
                            Name = "Челябинск",
                            Region = "Челябинская область"
                        },
                        new
                        {
                            Id = 128,
                            Country = "Россия",
                            Latitude = 53.418599999999998,
                            Longitude = 58.970799999999997,
                            Name = "Магнитогорск",
                            Region = "Челябинская область"
                        },
                        new
                        {
                            Id = 129,
                            Country = "Россия",
                            Latitude = 55.171100000000003,
                            Longitude = 59.650799999999997,
                            Name = "Златоуст",
                            Region = "Челябинская область"
                        },
                        new
                        {
                            Id = 130,
                            Country = "Россия",
                            Latitude = 55.045299999999997,
                            Longitude = 60.1083,
                            Name = "Миасс",
                            Region = "Челябинская область"
                        },
                        new
                        {
                            Id = 131,
                            Country = "Россия",
                            Latitude = 55.116700000000002,
                            Longitude = 61.616700000000002,
                            Name = "Копейск",
                            Region = "Челябинская область"
                        },
                        new
                        {
                            Id = 132,
                            Country = "Россия",
                            Latitude = 57.152200000000001,
                            Longitude = 65.527199999999993,
                            Name = "Тюмень",
                            Region = "Тюменская область"
                        },
                        new
                        {
                            Id = 133,
                            Country = "Россия",
                            Latitude = 58.198099999999997,
                            Longitude = 68.254199999999997,
                            Name = "Тобольск",
                            Region = "Тюменская область"
                        },
                        new
                        {
                            Id = 134,
                            Country = "Россия",
                            Latitude = 61.25,
                            Longitude = 73.416700000000006,
                            Name = "Сургут",
                            Region = "Ханты-Мансийский автономный округ"
                        },
                        new
                        {
                            Id = 135,
                            Country = "Россия",
                            Latitude = 60.934399999999997,
                            Longitude = 76.553100000000001,
                            Name = "Нижневартовск",
                            Region = "Ханты-Мансийский автономный округ"
                        },
                        new
                        {
                            Id = 136,
                            Country = "Россия",
                            Latitude = 61.099699999999999,
                            Longitude = 72.603899999999996,
                            Name = "Нефтеюганск",
                            Region = "Ханты-Мансийский автономный округ"
                        },
                        new
                        {
                            Id = 137,
                            Country = "Россия",
                            Latitude = 55.441099999999999,
                            Longitude = 65.341099999999997,
                            Name = "Курган",
                            Region = "Курганская область"
                        },
                        new
                        {
                            Id = 138,
                            Country = "Россия",
                            Latitude = 55.008400000000002,
                            Longitude = 82.935699999999997,
                            Name = "Новосибирск",
                            Region = "Новосибирская область"
                        },
                        new
                        {
                            Id = 139,
                            Country = "Россия",
                            Latitude = 54.757800000000003,
                            Longitude = 83.104399999999998,
                            Name = "Бердск",
                            Region = "Новосибирская область"
                        },
                        new
                        {
                            Id = 140,
                            Country = "Россия",
                            Latitude = 56.015300000000003,
                            Longitude = 92.893199999999993,
                            Name = "Красноярск",
                            Region = "Красноярский край"
                        },
                        new
                        {
                            Id = 141,
                            Country = "Россия",
                            Latitude = 69.353499999999997,
                            Longitude = 88.202699999999993,
                            Name = "Норильск",
                            Region = "Красноярский край"
                        },
                        new
                        {
                            Id = 142,
                            Country = "Россия",
                            Latitude = 56.269399999999997,
                            Longitude = 90.499399999999994,
                            Name = "Ачинск",
                            Region = "Красноярский край"
                        },
                        new
                        {
                            Id = 143,
                            Country = "Россия",
                            Latitude = 54.988500000000002,
                            Longitude = 73.324200000000005,
                            Name = "Омск",
                            Region = "Омская область"
                        },
                        new
                        {
                            Id = 144,
                            Country = "Россия",
                            Latitude = 53.354799999999997,
                            Longitude = 83.769800000000004,
                            Name = "Барнаул",
                            Region = "Алтайский край"
                        },
                        new
                        {
                            Id = 145,
                            Country = "Россия",
                            Latitude = 52.5364,
                            Longitude = 85.2072,
                            Name = "Бийск",
                            Region = "Алтайский край"
                        },
                        new
                        {
                            Id = 146,
                            Country = "Россия",
                            Latitude = 51.533299999999997,
                            Longitude = 81.216700000000003,
                            Name = "Рубцовск",
                            Region = "Алтайский край"
                        },
                        new
                        {
                            Id = 147,
                            Country = "Россия",
                            Latitude = 52.286999999999999,
                            Longitude = 104.30500000000001,
                            Name = "Иркутск",
                            Region = "Иркутская область"
                        },
                        new
                        {
                            Id = 148,
                            Country = "Россия",
                            Latitude = 56.1325,
                            Longitude = 101.6142,
                            Name = "Братск",
                            Region = "Иркутская область"
                        },
                        new
                        {
                            Id = 149,
                            Country = "Россия",
                            Latitude = 52.544400000000003,
                            Longitude = 103.8883,
                            Name = "Ангарск",
                            Region = "Иркутская область"
                        },
                        new
                        {
                            Id = 150,
                            Country = "Россия",
                            Latitude = 48.481400000000001,
                            Longitude = 135.07210000000001,
                            Name = "Хабаровск",
                            Region = "Хабаровский край"
                        },
                        new
                        {
                            Id = 151,
                            Country = "Россия",
                            Latitude = 50.549999999999997,
                            Longitude = 137.0,
                            Name = "Комсомольск-на-Амуре",
                            Region = "Хабаровский край"
                        },
                        new
                        {
                            Id = 152,
                            Country = "Россия",
                            Latitude = 43.119799999999998,
                            Longitude = 131.8869,
                            Name = "Владивосток",
                            Region = "Приморский край"
                        },
                        new
                        {
                            Id = 153,
                            Country = "Россия",
                            Latitude = 43.797199999999997,
                            Longitude = 131.95419999999999,
                            Name = "Уссурийск",
                            Region = "Приморский край"
                        },
                        new
                        {
                            Id = 154,
                            Country = "Россия",
                            Latitude = 42.813899999999997,
                            Longitude = 132.87360000000001,
                            Name = "Находка",
                            Region = "Приморский край"
                        },
                        new
                        {
                            Id = 155,
                            Country = "Россия",
                            Latitude = 43.355600000000003,
                            Longitude = 132.18889999999999,
                            Name = "Артём",
                            Region = "Приморский край"
                        },
                        new
                        {
                            Id = 156,
                            Country = "Россия",
                            Latitude = 56.497700000000002,
                            Longitude = 84.974400000000003,
                            Name = "Томск",
                            Region = "Томская область"
                        },
                        new
                        {
                            Id = 157,
                            Country = "Россия",
                            Latitude = 56.600000000000001,
                            Longitude = 84.849999999999994,
                            Name = "Северск",
                            Region = "Томская область"
                        },
                        new
                        {
                            Id = 158,
                            Country = "Россия",
                            Latitude = 55.354700000000001,
                            Longitude = 86.088800000000006,
                            Name = "Кемерово",
                            Region = "Кемеровская область"
                        },
                        new
                        {
                            Id = 159,
                            Country = "Россия",
                            Latitude = 53.759599999999999,
                            Longitude = 87.121600000000001,
                            Name = "Новокузнецк",
                            Region = "Кемеровская область"
                        },
                        new
                        {
                            Id = 160,
                            Country = "Россия",
                            Latitude = 53.883299999999998,
                            Longitude = 86.716700000000003,
                            Name = "Прокопьевск",
                            Region = "Кемеровская область"
                        },
                        new
                        {
                            Id = 161,
                            Country = "Россия",
                            Latitude = 51.834800000000001,
                            Longitude = 107.5844,
                            Name = "Улан-Удэ",
                            Region = "Республика Бурятия"
                        },
                        new
                        {
                            Id = 162,
                            Country = "Россия",
                            Latitude = 52.031700000000001,
                            Longitude = 113.5009,
                            Name = "Чита",
                            Region = "Забайкальский край"
                        },
                        new
                        {
                            Id = 163,
                            Country = "Россия",
                            Latitude = 62.035499999999999,
                            Longitude = 129.6755,
                            Name = "Якутск",
                            Region = "Республика Саха (Якутия)"
                        },
                        new
                        {
                            Id = 164,
                            Country = "Россия",
                            Latitude = 50.279600000000002,
                            Longitude = 127.54049999999999,
                            Name = "Благовещенск",
                            Region = "Амурская область"
                        },
                        new
                        {
                            Id = 165,
                            Country = "Россия",
                            Latitude = 46.959200000000003,
                            Longitude = 142.7381,
                            Name = "Южно-Сахалинск",
                            Region = "Сахалинская область"
                        },
                        new
                        {
                            Id = 166,
                            Country = "Россия",
                            Latitude = 53.045200000000001,
                            Longitude = 158.65090000000001,
                            Name = "Петропавловск-Камчатский",
                            Region = "Камчатский край"
                        },
                        new
                        {
                            Id = 167,
                            Country = "Россия",
                            Latitude = 53.715600000000002,
                            Longitude = 91.429199999999994,
                            Name = "Абакан",
                            Region = "Республика Хакасия"
                        },
                        new
                        {
                            Id = 168,
                            Country = "Россия",
                            Latitude = 51.719700000000003,
                            Longitude = 94.437799999999996,
                            Name = "Кызыл",
                            Region = "Республика Тыва"
                        },
                        new
                        {
                            Id = 169,
                            Country = "Беларусь",
                            Latitude = 53.900599999999997,
                            Longitude = 27.559000000000001,
                            Name = "Минск",
                            Region = "Минская область"
                        },
                        new
                        {
                            Id = 170,
                            Country = "Беларусь",
                            Latitude = 52.4345,
                            Longitude = 30.9754,
                            Name = "Гомель",
                            Region = "Гомельская область"
                        },
                        new
                        {
                            Id = 171,
                            Country = "Беларусь",
                            Latitude = 53.898099999999999,
                            Longitude = 30.3325,
                            Name = "Могилёв",
                            Region = "Могилёвская область"
                        },
                        new
                        {
                            Id = 172,
                            Country = "Беларусь",
                            Latitude = 55.190399999999997,
                            Longitude = 30.204899999999999,
                            Name = "Витебск",
                            Region = "Витебская область"
                        },
                        new
                        {
                            Id = 173,
                            Country = "Беларусь",
                            Latitude = 53.668799999999997,
                            Longitude = 23.829499999999999,
                            Name = "Гродно",
                            Region = "Гродненская область"
                        },
                        new
                        {
                            Id = 174,
                            Country = "Беларусь",
                            Latitude = 52.0976,
                            Longitude = 23.734100000000002,
                            Name = "Брест",
                            Region = "Брестская область"
                        },
                        new
                        {
                            Id = 175,
                            Country = "Казахстан",
                            Latitude = 51.169400000000003,
                            Longitude = 71.449100000000001,
                            Name = "Астана",
                            Region = "Акмолинская область"
                        },
                        new
                        {
                            Id = 176,
                            Country = "Казахстан",
                            Latitude = 43.222000000000001,
                            Longitude = 76.851200000000006,
                            Name = "Алматы",
                            Region = "Алматинская область"
                        },
                        new
                        {
                            Id = 177,
                            Country = "Казахстан",
                            Latitude = 42.341700000000003,
                            Longitude = 69.590100000000007,
                            Name = "Шымкент",
                            Region = "Туркестанская область"
                        },
                        new
                        {
                            Id = 178,
                            Country = "Казахстан",
                            Latitude = 49.801900000000003,
                            Longitude = 73.102099999999993,
                            Name = "Караганда",
                            Region = "Карагандинская область"
                        },
                        new
                        {
                            Id = 179,
                            Country = "Казахстан",
                            Latitude = 50.283900000000003,
                            Longitude = 57.167000000000002,
                            Name = "Актобе",
                            Region = "Актюбинская область"
                        },
                        new
                        {
                            Id = 180,
                            Country = "Узбекистан",
                            Latitude = 41.299500000000002,
                            Longitude = 69.240099999999998,
                            Name = "Ташкент",
                            Region = "Ташкентская область"
                        },
                        new
                        {
                            Id = 181,
                            Country = "Узбекистан",
                            Latitude = 39.654200000000003,
                            Longitude = 66.959699999999998,
                            Name = "Самарканд",
                            Region = "Самаркандская область"
                        },
                        new
                        {
                            Id = 182,
                            Country = "Кыргызстан",
                            Latitude = 42.874600000000001,
                            Longitude = 74.569800000000001,
                            Name = "Бишкек",
                            Region = "Чуйская область"
                        },
                        new
                        {
                            Id = 183,
                            Country = "Армения",
                            Latitude = 40.179200000000002,
                            Longitude = 44.499099999999999,
                            Name = "Ереван",
                            Region = "Ереван"
                        },
                        new
                        {
                            Id = 184,
                            Country = "Азербайджан",
                            Latitude = 40.409300000000002,
                            Longitude = 49.867100000000001,
                            Name = "Баку",
                            Region = "Баку"
                        },
                        new
                        {
                            Id = 185,
                            Country = "Грузия",
                            Latitude = 41.7151,
                            Longitude = 44.827100000000002,
                            Name = "Тбилиси",
                            Region = "Тбилиси"
                        });
                });

            modelBuilder.Entity("DatingBot.Domain.Entities.Interest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_Interests_Code");

                    b.ToTable("Interests", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = 1,
                            Icon = "🎵",
                            Title = "Музыка"
                        },
                        new
                        {
                            Id = 2,
                            Code = 2,
                            Icon = "🎮",
                            Title = "Видеоигры"
                        },
                        new
                        {
                            Id = 3,
                            Code = 3,
                            Icon = "🎬",
                            Title = "Фильмы"
                        },
                        new
                        {
                            Id = 4,
                            Code = 4,
                            Icon = "⛩️",
                            Title = "Аниме"
                        },
                        new
                        {
                            Id = 5,
                            Code = 5,
                            Icon = "⚽",
                            Title = "Спорт"
                        },
                        new
                        {
                            Id = 6,
                            Code = 6,
                            Icon = "📚",
                            Title = "Книги"
                        },
                        new
                        {
                            Id = 7,
                            Code = 7,
                            Icon = "✈️",
                            Title = "Путешествия"
                        },
                        new
                        {
                            Id = 8,
                            Code = 8,
                            Icon = "🎨",
                            Title = "Искусство"
                        },
                        new
                        {
                            Id = 9,
                            Code = 9,
                            Icon = "🍳",
                            Title = "Кулинария"
                        },
                        new
                        {
                            Id = 10,
                            Code = 10,
                            Icon = "💻",
                            Title = "Технологии"
                        },
                        new
                        {
                            Id = 11,
                            Code = 11,
                            Icon = "🎲",
                            Title = "Настолки"
                        },
                        new
                        {
                            Id = 12,
                            Code = 12,
                            Icon = "🏕️",
                            Title = "Активный отдых"
                        });
                });

            modelBuilder.Entity("DatingBot.Domain.Entities.ProfileRating", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FromUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<Guid>("ToUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ToUserId");

                    b.HasIndex("FromUserId", "ToUserId")
                        .IsUnique()
                        .HasDatabaseName("IX_ProfileRatings_FromUser_ToUser");

                    b.ToTable("ProfileRatings", (string)null);
                });

            modelBuilder.Entity("DatingBot.Domain.Entities.ProfileReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Reason")
                        .HasColumnType("int");

                    b.Property<Guid>("ReportedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ReporterId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ReportedUserId");

                    b.HasIndex("ReporterId", "ReportedUserId")
                        .HasDatabaseName("IX_ProfileReports_Reporter_Reported");

                    b.ToTable("ProfileReports", (string)null);
                });

            modelBuilder.Entity("DatingBot.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CurrentCandidateProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("LastBotMessageId")
                        .HasColumnType("int");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<long>("TelegramId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("TelegramId")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_TelegramId");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("DatingBot.Domain.Entities.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<int>("AgeFilters")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("AiDescription")
                        .HasMaxLength(2500)
                        .HasColumnType("nvarchar(2500)");

                    b.Property<byte[]>("AiVector")
                        .HasMaxLength(1536)
                        .HasColumnType("varbinary(1536)");

                    b.Property<double>("AverageRating")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.0);

                    b.Property<string>("City")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("CityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DatingTarget")
                        .HasColumnType("int");

                    b.Property<int?>("Gender")
                        .HasColumnType("int");

                    b.Property<int?>("Height")
                        .HasColumnType("int");

                    b.Property<bool>("IsCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhotoFileId")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("RatingCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int?>("SearchMaxAge")
                        .HasColumnType("int");

                    b.Property<int?>("SearchMinAge")
                        .HasColumnType("int");

                    b.Property<int?>("TargetGender")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("City")
                        .HasDatabaseName("IX_UserProfiles_City");

                    b.HasIndex("CityId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.HasIndex("IsCompleted", "Gender", "TargetGender", "DatingTarget")
                        .HasDatabaseName("IX_UserProfiles_Matchmaking_Filter");

                    b.ToTable("UserProfiles", (string)null);
                });

            modelBuilder.Entity("DatingBot.Domain.Entities.UserProfileInterest", b =>
                {
                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("InterestId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("UserProfileId", "InterestId");

                    b.HasIndex("InterestId");

                    b.ToTable("UserProfileInterests", (string)null);
                });

            modelBuilder.Entity("DatingBot.Domain.Entities.ProfileRating", b =>
                {
                    b.HasOne("DatingBot.Domain.Entities.User", "FromUser")
                        .WithMany()
                        .HasForeignKey("FromUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DatingBot.Domain.Entities.User", "ToUser")
                        .WithMany()
                        .HasForeignKey("ToUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromUser");

                    b.Navigation("ToUser");
                });

            modelBuilder.Entity("DatingBot.Domain.Entities.ProfileReport", b =>
                {
                    b.HasOne("DatingBot.Domain.Entities.User", "ReportedUser")
                        .WithMany()
                        .HasForeignKey("ReportedUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DatingBot.Domain.Entities.User", "Reporter")
                        .WithMany()
                        .HasForeignKey("ReporterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ReportedUser");

                    b.Navigation("Reporter");
                });

            modelBuilder.Entity("DatingBot.Domain.Entities.UserProfile", b =>
                {
                    b.HasOne("DatingBot.Domain.Entities.City", "CityRef")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DatingBot.Domain.Entities.User", "User")
                        .WithOne("Profile")
                        .HasForeignKey("DatingBot.Domain.Entities.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CityRef");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DatingBot.Domain.Entities.UserProfileInterest", b =>
                {
                    b.HasOne("DatingBot.Domain.Entities.Interest", "Interest")
                        .WithMany("UserProfiles")
                        .HasForeignKey("InterestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DatingBot.Domain.Entities.UserProfile", "UserProfile")
                        .WithMany("Interests")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Interest");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("DatingBot.Domain.Entities.Interest", b =>
                {
                    b.Navigation("UserProfiles");
                });

            modelBuilder.Entity("DatingBot.Domain.Entities.User", b =>
                {
                    b.Navigation("Profile");
                });

            modelBuilder.Entity("DatingBot.Domain.Entities.UserProfile", b =>
                {
                    b.Navigation("Interests");
                });
#pragma warning restore 612, 618
        }
    }
}
